version: "3"

services:
  bot:
    build: .
    container_name: pingubot
    command:
      - scripts/start.sh
    depends_on:
      - db
    environment:
      - PINGU_TOKEN
      - PGHOST
      - PGUSER
      - PGDATABASE
      - PGPASSWORD
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    image: pingubot:latest
    restart: on-failure
    user: pingu:pingu

  db:
    container_name: pingubot-db
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    image: postgres:latest
    # Only needed if the host needs to access it
    # ports:
    #   - "5432:5432"
    restart: unless-stopped
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/template.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  postgres-data: