version: "3.8"

services:
  bot:
    build: .
    container_name: pingubot
    command:
      - scripts/start.sh
    depends_on:
      - audio
      - db
    environment:
      - LAVALINK_PASSWORD
      - LAVALINK_REGION
      - PINGU_TOKEN
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    image: pingubot:latest
    networks:
      - bot_network
    restart: on-failure
    user: pingu:pingu

  audio:
    container_name: pingubot-audio
    image: fredboat/lavalink:master-v3
    networks:
      - bot_network
    restart: always
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml:ro
      - ./soundfx:/opt/Lavalink/soundfx:ro

  db:
    container_name: pingubot-db
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    image: postgres:13
    # Only needed if the host needs to access it
    # ports:
    #   - "5432:5432"
    networks:
      - bot_network
    restart: always
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # - ./database/template.sql:/docker-entrypoint-initdb.d/init.sql:ro

networks:
  bot_network:
    name: pingubot_network

volumes:
  postgres-data:
    name: pingubot-data