version: "3.8"

services:
  bot:
    build: .
    container_name: pingubot
    command:
      - scripts/start.sh
    depends_on:
      - audio
      - db
    environment:
      - LAVALINK_HOST
      - LAVALINK_PORT
      - LAVALINK_PASSWORD
      - LAVALINK_REGION
      - PINGU_TOKEN
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    image: pingubot:latest
    networks:
      - bot_network
    restart: on-failure
    user: pingu:pingu

  audio:
    build:
      context: ./lavalink
      args:
        - LAVALINK_PORT
        - LAVALINK_PASSWORD
    container_name: pingulink
    image: pingulink:latest
    networks:
      - bot_network
    restart: always

  db:
    container_name: pingudb
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    image: postgres:13
    # ports:
    #   - "5432:5432"
    networks:
      - bot_network
    restart: always
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  bot_network:
    name: pingubot_network

volumes:
  postgres-data:
    name: pingubot-data
