[tool.poetry]
name = "pingubot"
version = "2.1"
description = ""
authors = ["nootify"]

[tool.poetry.dependencies]
python = ">=3.10,<4"
python-dotenv = "^1.0.0"
"discord.py" = {extras = ["voice"], version = "^2.2.2"}
jishaku = "^2.5.1"
wavelink = "^2.1.0"
psutil = "^5.9.5"
pytz = "^2023.3"
pytimeparse = "^1.1.8"
SQLAlchemy = "^2.0.13"
asyncpg = "^0.27.0"
arrow = "^1.2.3"
humanize = "^4.6.0"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
black = "^23.3.0"

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
