[tool.poetry]
name = "pingubot"
version = "2.0"
description = ""
authors = ["nootify"]

[tool.poetry.dependencies]
python = ">=3.8,<4"
python-dotenv = "^0.20.0"
"discord.py" = {extras = ["voice"], version = "^2.0.0"}
jishaku = "^2.5.1"
wavelink = "^1.3.2"
psutil = "^5.9.3"
pytz = "^2022.2.1"
pytimeparse = "^1.1.8"
SQLAlchemy = {extras = ["asyncio"], version = "^1.4.40"}
asyncpg = "^0.26.0"
arrow = "^1.2.2"
humanize = "^4.3.0"

[tool.poetry.dev-dependencies]
coverage = "^6.4.4"
flake8 = "^5.0.4"
black = "^22.6.0"

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
