[tool.poetry]
name = "pingubot"
version = "0.0.5"
description = ""
authors = ["nootify"]

[tool.poetry.dependencies]
python = "^3.8"
python-dotenv = "^0.17.1"
"discord.py" = {extras = ["voice"], version = "^1.7.2"}
jishaku = "^1.20.0"
asyncpg = "^0.23.0"
gino = "^1.0.1"
wavelink = "^0.9.9"
aiofiles = "^0.7.0"
prettytable = "^2.1.0"
psutil = "^5.8.0"
pytz = "^2021.1"

[tool.poetry.dev-dependencies]
coverage = "^5.5"
flake8 = "^3.9.2"
black = "^21.5b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
